name: GitHub Actions Extract

on:
    schedule:
        - cron: '*/60 * * * *'

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:

            - name: checkout repo content
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.5'

            - name: install pandas
              run: |
                python -m pip install --upgrade pip
                pip install pandas

            - name: execute py script
              run: python SRC/extract/extract_and_save_daya.py

            - name: commit and push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: "up model.pkl"
