name: GitHub Actions Extract

on:
    schedule:
        - cron: '1 * * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-lastest
        steps:

            - name: checkout repo content
              run: echo "hello world"
