# This is a basic workflow to help you get started with Actions

name:
    Extract Cron Job

    # Controls when the workflow will run
on:
    # Triggers the workflow every 5 minutes
    schedule:
      - cron: "0 5 * * *"
    workflow_dispatch:

        # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    cron:

      runs-on: ubuntu-latest

      steps:

        - name: Check conteudo do repositorio
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Instala python 3.11.5
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.5'

        - name: Instalação das dependências
          run: |
            python -m pip install --upgrade pip
            pip install pandas pyarrow fastparquet

        - name: Execução script python
          run: |
            python SRC/extract/extract_and_save_data.py
